const courseList = {
    courseCategories: [
        {
            id: "1",
            image: require("../../images/c1.jpg"),
            title: "The Power of Podcast for Storytelling",
            rating: "4.5",
            lessons: 10,
            enrolled: 28,
            price: 36.00,
            instructor: "Lewis",
            courseCategory1: "Finance",
            courseCategory2: "LifeStyle",
            courseCategory3: "",
            courseCategory4: "",
        },
        {
            id: "2",
            image: "https://i.ibb.co/F8X3Rpy/c2.jpg",
            title: "Fashion and Luxury Fashion in a Changing",
            rating: "4.5",
            lessons: 8,
            enrolled: 2,
            price: 19.00,
            instructor: "Lewis",
            courseCategory1: "Finance",
            courseCategory2: "LifeStyle",
            courseCategory3: "",
            courseCategory4: "",
        },
        {
            id: "3",
            image: "https://i.ibb.co/0YZn4TG/c3.jpg",
            title: "Creative writing through Storytelling",
            rating: "4.0",
            lessons: 12,
            enrolled: 12,
            price: 30.00,
            instructor: "Educal",
            courseCategory1: "",
            courseCategory2: "",
            courseCategory3: "Data Science",
            courseCategory4: "Marketing",
        },
        {
            id: "4",
            image: "https://i.ibb.co/thwbsX2/c4.jpg",
            title: "Improving The Accessibility Of Your Markdown",
            rating: "4.5",
            lessons: 10,
            enrolled: 20,
            price: 36.00,
            instructor: "Lewis",
            courseCategory1: "Finance",
            courseCategory2: "LifeStyle",
            courseCategory3: "",
            courseCategory4: "",
        },
        {
            id: "5",
            image: "https://i.ibb.co/f2M5nD3/c5.jpg",
            title: "Product Manager Learn the Skills & job.",
            rating: "4.8",
            lessons: 5,
            enrolled: 10,
            price: 52.00,
            instructor: "Educal",
            courseCategory1: "",
            courseCategory2: "LifeStyle",
            courseCategory3: "",
            courseCategory4: "",
        },
        {
            id: "6",
            image: "https://i.ibb.co/Zh8HS56/c6.jpg",
            title: "The business Intelligence analyst Course 2022",
            rating: "4.9",
            lessons: 4,
            enrolled: 11,
            price: 25.00,
            instructor: "Educal",
            courseCategory1: "Finance",
            courseCategory2: "",
            courseCategory3: "",
            courseCategory4: "Marketing",
        },
    ]
}
export default courseList;